# Generated by Django 6.0.1 on 2026-02-01 12:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Optional. Enter a valid phone number.', max_length=16, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+254700123456' or '0700123456'. Up to 15 digits allowed.", regex='^\\+?\\d{9,15}$')]),
        ),
    ]
