# Generated by Django 6.0.1 on 2026-01-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactform', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='subject',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='subject_type',
            field=models.CharField(choices=[('general', 'General Inquiry'), ('vehicle', 'Vehicle Inquiry'), ('test_drive', 'Test Drive Request'), ('financing', 'Financing Question')], default='General', max_length=20),
            preserve_default=False,
        ),
    ]
