# Generated by Django 6.0.1 on 2026-01-22 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactform', '0002_remove_contactmessage_subject_contactmessage_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='subject_type',
            field=models.CharField(choices=[('General', 'General Inquiry'), ('Vehicle', 'Vehicle Inquiry'), ('Test_drive', 'Test Drive Request'), ('Financing', 'Financing Question')], max_length=20),
        ),
    ]
