# Generated by Django 6.0.1 on 2026-01-22 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car_stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('sold', 'Sold')], default='available', max_length=20)),
                ('year', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=120)),
                ('drive_type', models.CharField(choices=[('fwd', 'Front‑wheel drive'), ('rwd', 'Rear‑wheel drive'), ('awd', 'All‑wheel drive'), ('4wd', '4‑wheel drive')], max_length=10)),
                ('mileage', models.PositiveIntegerField(help_text='Mileage in km')),
                ('engine_capacity_cc', models.PositiveIntegerField()),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('hybrid', 'Hybrid'), ('electric', 'Electric')], max_length=10)),
                ('horsepower', models.PositiveIntegerField()),
                ('transmission', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], max_length=10)),
                ('torque_nm', models.PositiveIntegerField(help_text='Torque in Nm')),
                ('top_speed_kmh', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'car_inventory',
            },
        ),
        migrations.CreateModel(
            name='CarImage_stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='inventory.car_stocks')),
            ],
            options={
                'db_table': 'car_inventory_images',
            },
        ),
    ]
