# Generated by Django 6.0.1 on 2026-01-13 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('SUV', 'SUV'), ('Sedan', 'Sedan'), ('Truck', 'Truck'), ('Coupe', 'Coupe'), ('Hatchback', 'Hatchback')], max_length=50)),
                ('drive_type', models.CharField(default='4WD', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('year', models.PositiveIntegerField()),
                ('mileage', models.PositiveIntegerField(help_text='Mileage in KM')),
                ('fuel_type', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Hybrid', 'Hybrid'), ('Electric', 'Electric')], max_length=50)),
                ('transmission', models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual')], max_length=50)),
                ('key_features', models.TextField(help_text='Comma-separated list of features')),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='cars/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
