# Generated by Django 6.0.1 on 2026-01-25 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car_stocks',
            name='discount_percent',
            field=models.PositiveIntegerField(default=0, help_text='Discount %'),
        ),
        migrations.AddField(
            model_name='car_stocks',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
