# Generated by Django 6.0.1 on 2026-01-13 23:04

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_car_image_alter_car_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='carimage',
            options={'ordering': ['order', 'uploaded_at']},
        ),
        migrations.AddField(
            model_name='car',
            name='brand',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='color_exterior',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='color_interior',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='doors',
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='car',
            name='engine_size',
            field=models.CharField(blank=True, help_text='e.g., 2.5L, 3.0L', max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='negotiable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='seats',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('reserved', 'Reserved'), ('pending', 'Pending')], default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='car',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='car',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carimage',
            name='caption',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='carimage',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carimage',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='category',
            field=models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('truck', 'Truck'), ('coupe', 'Coupe'), ('convertible', 'Convertible'), ('wagon', 'Wagon'), ('van', 'Van'), ('hatchback', 'Hatchback')], max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='drive_type',
            field=models.CharField(choices=[('fwd', 'Front Wheel Drive'), ('rwd', 'Rear Wheel Drive'), ('awd', 'All Wheel Drive'), ('4wd', '4 Wheel Drive')], default='4wd', max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('hybrid', 'Hybrid'), ('plug_in_hybrid', 'Plug-in Hybrid')], max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='key_features',
            field=models.TextField(help_text='Comma-separated features'),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='car',
            name='title',
            field=models.CharField(help_text='e.g., Toyota Land Cruiser VX', max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic'), ('cvt', 'CVT'), ('semi_automatic', 'Semi-Automatic')], max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2027)]),
        ),
        migrations.AlterField(
            model_name='carimage',
            name='image',
            field=models.ImageField(upload_to='cars/%Y/%m/'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['status', '-created_at'], name='inventory_c_status_fd3611_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['category', 'price'], name='inventory_c_categor_3909d2_idx'),
        ),
        migrations.AddIndex(
            model_name='carimage',
            index=models.Index(fields=['car', 'is_primary'], name='inventory_c_car_id_0ee805_idx'),
        ),
    ]
