# Generated by Django 6.0.1 on 2026-01-25 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_car_stocks_discount_percent_car_stocks_final_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_stocks',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount % (e.g., 15.50 for 15.5%)', max_digits=5),
        ),
    ]
